#!bin/bash
#
for kasutaja in $(ls /home)
do
#vaatame iga kasutaja kodukatalooma ja kontrollime, kas on public kataloom
ls /home/$kasutaja | grep public > /dev/null
#kui public on leitud, on käsi exit status 0
#kui ei leita, on 1
if [ $? -eq 1 ]; then
#sel juhul loome antud katalooma
mkdir /home/$kasutaja/public && chown -R $kasutaja:$kasutaja /home/$kasutaja/public && chmod 751 /home/$kasutaja/public
#kontrollime tulemust
if [ $? -eq 0 ]; then
echo "Kasutaja nimega $kasutaja kodukaustas on Public loodud."
ls -la /home/$kasutajanimi
else
echo "Probleem kasutaja $kasutajanimi Public kausta loomisega!"
echo "Probleemi kood $?"
fi
#kui public kaust on juba olemas, teavitame sellest
else
echo "Kasutaja $kasutaja kodukaustas on Public juba olemas!"
fi
done
