#!bin/bash
#Kasutaja public kausta lisamise skpript
#kasutajanimi tuleb anda skripti parameetrina
#Võime lisada ka kasutusjuhendi puhuks kui midagi valesti käivitame või unustame
#Käsurea kaudu on parameetrite arv $# sees olev number. Meie puhul peab olema 1 parameeter - kasutajanimi
#kui aga antud parameeter pole lisatud, tuleb kasutajat juhendada
#
if [ $# -ne 1 ]; then
echo "Kasutusjuhend: $0 kasutajanimi"
else
#defineerime vajaliku muutuja kasutajanime salvestamiseks
kasutajanimi=$1
#lisame vajaliku katalooma
#määrame vajalikud õigused
mkdir /home/$kasutajanimi/public && chown -R $kasutajanimi:$kasutajanimi /home/$kasutajanimi/public && chmod 751 /home/$kasutajanimi/public
#kontrollime käsu tulemust
if [ $? -eq 0 ]; then
echo "Kasutaja nimega $kasutajanimi on kodukaustas Public loodud."
cat /etc/passwd | grep $kasutajanimi
ls -la /home/$kasutajanimi
else
echo "Probleem kasutaja $kasutajanimi lisamisega!"
echo "Probleemi kood $?"
fi
fi
