#!bin/bash
#
#Raul Jaanson
#
#Skript kasutajate loomiseks failist
if [ $# -ne 1 ]; then
echo "Kasutusjuhend: $0 failinimi"
else
failinimi=$1
if [ -f $failinimi -a -r $failinimi ]; then
echo "Fail on OK!"
for nimi in $(cat $failinimi)
do
#Sellega peaks faili sisu nähtav olema kui fail on kättesaadav. Nüüd kutsume vajaliku skripti
sh kasutajalisamine $nimi
echo "$rida" | chpasswd # antud võimaldab määrata kasutajale parooli
done
else
echo "Probleem failiga $failinimi"
fi
fi
