#!bin/bash
#
#kasutaja lisamine
if [ $# -ne 1 ]; then 
echo "Kasutusjuhend: $0 kasutajanimi"
else
#defineerin vajaliku muutuja kasutajanime salvestamiseks 
#kuna andmed edastatakse käsurealt skripti parameetrina,
#siis on need ¤1 ja ¤2 jne
kasutajanimi=$1
#kasutame kasutaja lisamise käsku vajalike võtmetega
useradd $kasutajanimi -m -s /bin/bash
#kontrollime tulemust
if [ $? -eq 0 ]; then
echo "Kasutaja nimega $kasutajanimi on süsteemi lisatud"
cat /etc/passwd | grep $kasutajanimi
ls -la /home/$kasutajanimi
else
echo "Probleem kasutaja $kasutajanimi lisamisega"
echo "Probleemi kood $?"
fi
fi
