#!/bin/bash
cat /etc/passwd | grep /home | cut -d: -f1 > kasutaja
while IFS= read line
do
nimi=$(echo "$line")
if [ -f /home/$nimi/.my.cnf ]
then
echo "Fail on olemas" $nimi
else
echo "Faili pole kasutajal" $nimi
pass=$(pwgen -s 10 1)
echo "Loon faili kasutajale" $nimi
prinf "[client]\nuser=$nimi\npassword=$pass\n" > /home/$nimi/.my.cnf
mysql -e "CREATE DATABASE ${kasutaja}"
mysql -e "CREATE USER ${kasutaja}"localhost IDENTIFIED BY '${parool}';"
mysql -e "GRANT ALL PRIVILEGES ON ${kasutaja}.* TO '${kasutaja}'"'localhost':"
mysql -e "FLUSH PRIVILEGES;"

fi
done < kasutajad
